
vocab1 = ["Livid - very angry",
 "Viand - an item of food",
 "Crony - a close friend",
 "Demure - quiet, polite",
 "Harlot - Prostitute",
 "Sordid - very bad, dishonest",
 "Domicile - a dwelling place",
 "Atrocious - very bad, wicked",
 "Sentiment - an attitude or opinion, feelings of love, sympathy or kindness",
 "Ruffian - a violent and strong person",
 "Elation - state of being elated, euphoria",
 "Feverish - having a fever / showing intense emotion or activity",
 "Dejected - sad because of failure or loss",
 "Morose - very unhappy or sad",
 "Abstruse - difficult to understand",
 "Malodorous - having a bad smell",
 "Sagacious - having the ability to understand difficult problems and ideas and to make good decisions",
"Blunder - to make a stupid careless mistake",
 "Radical - very basic and important",
 "Gaiety - a happy lively quality or high spirits",
 "Placid - not easily upset or excited",
 "Pious - falsely appearing to be good or moral",
 "Harangue - a forceful or angry speech",
 "Solitary - isolated ; done by a person who is alone ; without anyone or anything else : not involving or including anyone or anything else",
 "Mortify - cause someone to feel embarrassed and foolish",
 "Mirth - happiness and laughter",
 "Brazen - acting or done in a very open and shocking way without embarrassment or shame",
 "Chutzpah - personal confidence that allows someone to do something that may seem shocking to others ; supreme self-confidence",
 "Leer - to look at someone in an evilish or unpleasantly sexual way",
 "Hypocrisy - the behavior of people who do things thaf they tell other people not to do",
 "Hypocrite - a person who claims or pretends to have certain beliefs on what is right but who behaves jn a way that disagrees with those beliefs",
 "Precarious - not safe , strong , or steady",
 "Appalled - affected by strong feelings of shock and dismay",
 "Accentuate - ",
 "Ludicrous - very foolish",
 "Lunatic - Insane",
 "Louche - not reputable or decent",
 "Posh - elegant, faahionable",
 "Wee - very small: very early",
 "Myriad - a very large number of things",
 "Mutiny - forcible or passive resistance to authorities : obsolete",
 "Obsolete - no longer in use or no longer useful",
 "Obstinate - refusing to change your behavior or your ideas : stubborn",
 "Abhorrent - feeling of dislike or hatred",
 "Effusive - expressing a lot of emotion",
 "Incorrigible - not able to be corrected or changed",
 "Languid - showing very little energy , strength or activity",
 "Florid - very fancy or too fancy",
 "Humdrum - not interesting, boring",
 "Status Quo - the current state of affairs or situation",
 "Sine Qua Non - something that is absolutely needed",
 "Lax - not careful enough",
 "Jove - an expression for agreeing or surprisement and is usually used as by Jove.",
 "Ruminate - to think cafefully or deep about something",
 "Tumult - state of noisy confusion or disorder",
 "Iniquitous - very unfair or evil",
 "Quietus - death",
 "Stolid - showing little or no emotion",
 "Raucous - loud and unpleasant to listen to",
 "Spruce - neat, stylish"]
vocab1.sort()
for words in vocab1:
    print(words)
